{{- if and .Values.adsService.enabled .Values.adsService.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homechef.fullname" . }}-ads-service
  labels:
    {{- include "homechef.labels" . | nindent 4 }}
    app.kubernetes.io/component: ads-service
spec:
  {{- if .Values.adsService.ingress.className }}
  ingressClassName: {{ .Values.adsService.ingress.className }}
  {{- end }}
  {{- if .Values.adsService.ingress.tls }}
  tls:
    {{- range .Values.adsService.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.adsService.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "homechef.fullname" $ }}-ads-service
                port:
                  number: {{ $.Values.adsService.service.port }}
          {{- end }}
    {{- end }}
{{- end }}