{{- if .Values.databaseService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homechef.fullname" . }}-database-service
  labels:
    {{- include "homechef.labels" . | nindent 4 }}
    app.kubernetes.io/component: database-service
spec:
  type: {{ .Values.databaseService.service.type }}
  ports:
    - port: {{ .Values.databaseService.service.port }}
      targetPort: {{ .Values.databaseService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "homechef.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database-service
{{- end }}