apiVersion: v1
kind: Namespace
metadata:
  name: homechef
  labels:
    name: homechef
    app.kubernetes.io/name: homechef
    app.kubernetes.io/instance: homechef
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: homechef-platform
    app.kubernetes.io/managed-by: helm