{{- if .Values.orderService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homechef.fullname" . }}-order-service-config
  labels:
    {{- include "homechef.labels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
data:
  PORT: {{ .Values.orderService.env.PORT | quote }}
  HOST: {{ .Values.orderService.env.HOST | quote }}
  ENVIRONMENT: {{ .Values.orderService.env.ENVIRONMENT | quote }}
  CRON_ENABLED: {{ .Values.orderService.env.CRON_ENABLED | quote }}
  SSL_CERT_PATH: "/root/certs/tls.crt"
  SSL_KEY_PATH: "/root/certs/tls.key"
{{- end }}