{{- if and .Values.orderService.enabled .Values.orderService.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homechef.fullname" . }}-order-service
  labels:
    {{- include "homechef.labels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: {{ include "homechef.fullname" . }}-order-service
spec:
  {{- if .Values.orderService.ingress.className }}
  ingressClassName: {{ .Values.orderService.ingress.className }}
  {{- end }}
  {{- if .Values.orderService.ingress.tls }}
  tls:
    {{- range .Values.orderService.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.orderService.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "homechef.fullname" $ }}-order-service
                port:
                  number: {{ $.Values.orderService.service.port }}
          {{- end }}
    {{- end }}
{{- end }}